In [462]:
import os
os.getcwd()

path = '/Users/daylelee/Desktop/2024 DBB EXPERT/3_project'
os.chdir(path)
print(os.getcwd())

/Users/daylelee/Desktop/2024 DBB EXPERT/3_project

In [3]:
import pandas as pd
df1 = pd.read_excel('./data/DBB_21.2월 모집_장기/raw_2102모집(2102_2302)_해당(수정).xlsx')
#df2 = pd.read_excel('./data/yuji_2407.xlsx')
#df3 = pd.read_excel('./data/raw_모집계약유지율명세_월.xlsx')
#df4 = pd.read_excel('./data/raw_모집계약유지율명세_월_컬럼추가.xlsx')

In [464]:
#df = df3.drop(columns=["해당확정구분명"])
#unique_id = set(df['계약ID'])
len(set(df1['증권번호']))

5099

In [17]:
set(df1['판매플랜명'])

{'01종_해지환급금 지급형_납면적용_세만기',
 '02종_해지환급금 지급형_납면미적용_세만기',
 '03종_해지환급금 지급형_납면적용_갱신형',
 '04종_해지환급금 지급형_납면미적용_갱신형'}

In [19]:
df1.columns

Index(['기준년월', '모집년월', '해당확정구분코드', '해당확정구분명', '확정년월', '증권번호', '보험기간시작일자',
       '보험기간종료일자', '보험료유지회차', '개인단체구분명', '최종납입년월', '최종납입횟수', '만기년수', '경과년도',
       '경과월수', '납입중지여부', '납입면제구분코드', '상품군명', '상품명', '판매플랜명', '대표상품명',
       '계약자우편번호', '계약자성별명', '계약자연령', '계약자현재연령', '계약유형코드', '계약유형명', '계약상태코드',
       '계약상태명', '계약상태일자', '계약상태세부코드', '계약상태세부명', '계약상태세부일자', '주피보험자성별명',
       '주피보험자연령', '주피보험자현재연령', '주피보험자직업코드', '주피보험자상해급수명', '피보험자직업대분류명',
       '피보험자직업중분류명', '피보험자직업소분류명', '피보험자위험등급명', '수금자사원번호', '수금부문명', '수금본부명',
       '수금사업단명', '수금지점명', '배당상품여부', '연금상품여부', '장기판매채널명', 'PA본인계약여부',
       'PA가족계약여부', 'PA계약여부', '직원계약여부', '모집계약건수', '보유계약건수', '가입당시월납환산보험료',
       '모집계약환산보험료', '보유계약환산보험료', '잔존계약환산보험료', '납입계약환산보험료'],
      dtype='object')

In [468]:
df = df1[df1['판매플랜명'].isin(['01종_해지환급금 지급형_납면적용_세만기', '02종_해지환급금 지급형_납면미적용_세만기'])]
# df.drop(columns=["개인단체구분명"], inplace=True)

In [470]:
set(df['증권번호'])

{320210386945,
 320210362375,
 320210313225,
 320210264075,
 320210288653,
 320210321425,
 320210411537,
 320210362393,
 320210386970,
 320210321434,
 320210509850,
 320210386971,
 320210378785,
 320210280488,
 320210346024,
 320210395179,
 320210264108,
 320210362416,
 320210272318,
 320210518081,
 320210362438,
 320210337863,
 320210337867,
 320210452556,
 320210485326,
 320210313295,
 320210387025,
 320210452562,
 320210354260,
 320210346072,
 320210452575,
 320210444387,
 320210509924,
 320210509928,
 320210305131,
 320210346092,
 320210264173,
 320210264176,
 320210288753,
 320210264178,
 320210452597,
 320210509942,
 320210337916,
 320210526335,
 320210321536,
 320210485377,
 320210346119,
 320210329735,
 320210468999,
 320210509966,
 320210305167,
 320210460816,
 320210403478,
 320210518170,
 320210296987,
 320210452638,
 320210518175,
 320210305182,
 320210460831,
 320210346149,
 320210411689,
 320210264238,
 320210280622,
 320210444465,
 320210501824,
 320210452682,
 320210419914,
 320210436309,
 320210428122,
 320210280667,
 320210403551,
 320210280682,
 320210288878,
 320210338033,
 320210264307,
 320210329846,
 320210411766,
 320210460926,
 320210313474,
 320210297090,
 320210329861,
 320210526469,
 320210403589,
 320210501907,
 320210305302,
 320210288918,
 320210321690,
 320210370863,
 320210460983,
 320210452794,
 320210428219,
 320210403657,
 320210305354,
 320210338125,
 320210329938,
 320210280788,
 320210461012,
 320210297174,
 320210387288,
 320210485597,
 320210321758,
 320210510176,
 320210264417,
 320210461024,
 320210321767,
 320210518384,
 320210518390,
 320210477433,
 320210428282,
 320210518406,
 320210264458,
 320210485646,
 320210395543,
 320210395545,
 320210280860,
 320210477470,
 320210313632,
 320210526628,
 320210354596,
 320210362791,
 320210452903,
 320210297260,
 320210297266,
 320210510258,
 320210354614,
 320210313657,
 320210502084,
 320210305477,
 320210526661,
 320210452935,
 320210444743,
 320210371017,
 320210477521,
 320210436564,
 320210469341,
 320210485729,
 320210264555,
 320210321902,
 320210428401,
 320210526705,
 320210493942,
 320210412023,
 320210469374,
 320210477569,
 320210289161,
 320210510354,
 320210461203,
 320210518546,
 320210518556,
 320210272802,
 320210313763,
 320210330148,
 320210444834,
 320210321960,
 320210395691,
 320210289198,
 320210264623,
 320210444857,
 320210461245,
 320210272836,
 320210494021,
 320210510408,
 320210395722,
 320210461263,
 320210502224,
 320210362965,
 320210477657,
 320210362972,
 320210313820,
 320210387549,
 320210371169,
 320210313832,
 320210444911,
 320210420341,
 320210444919,
 320210264696,
 320210518650,
 320210444922,
 320210264698,
 320210518660,
 320210281111,
 320210338459,
 320210494109,
 320210297501,
 320210281120,
 320210371233,
 320210346662,
 320210494119,
 320210494124,
 320210363053,
 320210281140,
 320210264758,
 320210289343,
 320210313920,
 320210281151,
 320210371266,
 320210502335,
 320210322114,
 320210518724,
 320210387661,
 320210494162,
 320210264790,
 320210494174,
 320210338526,
 320210395876,
 320210526958,
 320210428655,
 320210436849,
 320210330355,
 320210526967,
 320210428664,
 320210264829,
 320210297598,
 320210264833,
 320210273025,
 320210264835,
 320210526980,
 320210264837,
 320210322183,
 320210273032,
 320210346759,
 320210322186,
 320210502412,
 320210412300,
 320210289422,
 320210314000,
 320210264849,
 320210510610,
 320210461458,
 320210436885,
 320210395925,
 320210518807,
 320210354971,
 320210314013,
 320210305836,
 320210486065,
 320210264881,
 320210363185,
 320210305845,
 320210379583,
 320210445120,
 320210371395,
 320210273092,
 320210502470,
 320210387785,
 320210264906,
 320210461513,
 320210518859,
 320210436941,
 320210273107,
 320210387795,
 320210273112,
 320210445152,
 320210469734,
 320210314087,
 320210297702,
 320210518890,
 320210510699,
 320210322283,
 320210281324,
 320210387819,
 320210355052,
 320210396016,
 320210264945,
 320210338678,
 320210346875,
 320210346879,
 320210445185,
 320210396039,
 320210453384,
 320210264970,
 320210518923,
 320210264990,
 320210477985,
 320210428834,
 320210461605,
 320210445223,
 320210404264,
 320210486189,
 320210453423,
 320210289584,
 320210305972,
 320210273218,
 320210445253,
 320210518983,
 320210306000,
 320210461650,
 320210330578,
 320210404309,
 320210445269,
 320210396122,
 320210519004,
 320210453473,
 320210371557,
 320210314216,
 320210494442,
 320210412525,
 320210314227,
 320210486260,
 320210273269,
 320210428918,
 320210281463,
 320210346998,
 320210461687,
 320210486265,
 320210453501,
 320210387969,
 320210494473,
 320210347029,
 320210437143,
 320210519063,
 320210461723,
 320210453535,
 320210453537,
 320210265123,
 320210412586,
 320210453548,
 320210355244,
 320210363442,
 320210494515,
 320210437174,
 320210428984,
 320210469944,
 320210273340,
 320210388031,
 320210273344,
 320210371652,
 320210494534,
 320210519114,
 320210445390,
 320210429013,
 320210420826,
 320210478172,
 320210486364,
 320210527324,
 320210502751,
 320210371687,
 320210461812,
 320210445430,
 320210347129,
 320210453626,
 320210306172,
 320210429052,
 320210461821,
 320210306177,
 320210322562,
 320210510982,
 320210404487,
 320210453639,
 320210461845,
 320210478235,
 320210502812,
 320210298015,
 320210379939,
 320210527402,
 320210273451,
 320210404529,
 320210396338,
 320210412725,
 320210322614,
 320210527414,
 320210445507,
 320210265286,
 320210527431,
 320210265287,
 320210502858,
 320210527437,
 320210371790,
 320210371796,
 320210453724,
 320210388189,
 320210494687,
 320210396386,
 320210371812,
 320210437356,
 320210404594,
 320210470133,
 320210314492,
 320210527486,
 320210527490,
 320210289924,
 320210363658,
 320210494731,
 320210494732,
 320210306318,
 320210388239,
 320210281748,
 320210511125,
 320210380055,
 320210453787,
 320210494749,
 320210486559,
 320210388263,
 320210380075,
 320210511153,
 320210429236,
 320210519350,
 320210527555,
 320210462020,
 320210388294,
 320210306374,
 320210494792,
 320210339151,
 320210290012,
 320210371933,
 320210519390,
 320210478430,
 320210462048,
 320210404704,
 320210273635,
 320210281827,
 320210290021,
 320210330989,
 320210412914,
 320210429299,
 320210412916,
 320210437498,
 320210494843,
 320210445692,
 320210462077,
 320210519421,
 320210478458,
 320210331009,
 320210412929,
 320210503044,
 320210519429,
 320210388358,
 320210429322,
 320210412945,
 320210429340,
 320210371996,
 320210265502,
 320210355615,
 320210429347,
 320210486695,
 320210322856,
 320210527660,
 320210265520,
 320210412983,
 320210347447,
 320210363834,
 320210404798,
 320210470336,
 320210281923,
 320210314699,
 320210339276,
 320210462157,
 320210281935,
 320210396624,
 320210281938,
 320210527699,
 320210265558,
 320210503127,
 320210298327,
 320210519514,
 320210470362,
 320210527713,
 320210273763,
 320210527716,
 320210511335,
 320210478568,
 320210445808,
 320210486777,
 320210519546,
 320210486783,
 320210486793,
 320210265614,
 320210494990,
 320210445840,
 320210306574,
 320210519575,
 320210322968,
 320210478618,
 320210413085,
 320210437662,
 320210347552,
 320210421286,
 320210478637,
 320210413111,
 320210470457,
 320210282050,
 320210380356,
 320210503238,
 320210421321,
 320210404939,
 320210503247,
 320210511443,
 320210347605,
 320210388570,
 320210265694,
 320210495073,
 320210273890,
 320210331235,
 320210298465,
 320210331238,
 320210347627,
 320210396780,
 320210380402,
 320210519669,
 320210273914,
 320210445950,
 320210527877,
 320210282117,
 320210380424,
 320210282130,
 320210405010,
 320210413204,
 320210405016,
 320210503336,
 320210306731,
 320210519724,
 320210306733,
 320210364078,
 320210462388,
 320210470581,
 320210503350,
 320210355892,
 320210306748,
 320210470603,
 320210437837,
 320210454228,
 320210282203,
 320210519774,
 320210527966,
 320210388703,
 320210405089,
 320210274019,
 320210364139,
 320210519788,
 320210413298,
 320210274040,
 320210274050,
 320210519812,
 320210396933,
 320210306823,
 320210306826,
 320210511626,
 320210413325,
 320210265873,
 320210347797,
 320210339606,
 320210347799,
 320210519832,
 320210388760,
 320210462490,
 320210290458,
 320210429724,
 320210478869,
 320210478878,
 320210364193,
 320210396963,
 320210315044,
 320210413358,
 320210315055,
 320210495282,
 320210380597,
 320210413371,
 320210519868,
 320210265919,
 320210331456,
 320210282311,
 320210397000,
 320210478931,
 320210315098,
 320210282335,
 320210511711,
 320210495334,
 320210421608,
 320210478959,
 320210290545,
 320210397042,
 320210495346,
 320210298744,
 320210462588,
 320210470781,
 320210397057,
 320210347913,
 320210388873,
 320210306953,
 320210388878,
 320210364303,
 320210388880,
 320210429840,
 320210446226,
 320210298774,
 320210528152,
 320210282392,
 320210323355,
 320210298781,
 320210397087,
 320210495399,
 320210347950,
 320210528175,
 320210405297,
 320210454450,
 320210429879,
 320210405309,
 320210511809,
 320210323396,
 320210495431,
 320210470860,
 320210528205,
 320210446285,
 320210282447,
 320210470865,
 320210495444,
 320210372565,
 320210520024,
 320210331615,
 320210487264,
 320210339817,
 320210290667,
 320210421743,
 320210470897,
 320210282485,
 320210348025,
 320210380796,
 320210520062,
 320210397183,
 320210356226,
 320210282499,
 320210454533,
 320210356243,
 320210356246,
 320210364439,
 320210503704,
 320210462744,
 320210520095,
 320210331683,
 320210462756,
 320210380835,
 320210405419,
 320210290732,
 320210405421,
 320210290736,
 320210438195,
 320210315319,
 320210298937,
 320210462779,
 320210266172,
 320210503742,
 320210413631,
 320210274370,
 320210528322,
 320210495556,
 320210323525,
 320210454603,
 320210307149,
 320210528337,
 320210405457,
 320210413650,
 320210446425,
 320210331739,
 320210339936,
 320210503785,
 320210339950,
 320210471025,
 320210282609,
 320210405494,
 320210487418,
 320210372733,
 320210266239,
 320210405506,
 320210430082,
 320210380940,
 320210520206,
 320210315409,
 320210266262,
 320210282646,
 320210397338,
 320210299036,
 320210479262,
 320210299045,
 320210446508,
 320210299060,
 320210503866,
 320210520251,
 320210438331,
 320210290877,
 320210471102,
 320210495687,
 320210315473,
 320210266322,
 320210520273,
 320210307281,
 320210520281,
 320210381020,
 320210307296,
 320210282722,
 320210397420,
 320210381038,
 320210430191,
 320210348277,
 320210430198,
 320210479353,
 320210307329,
 320210462978,
 320210422022,
 320210512135,
 320210307336,
 320210446614,
 320210462999,
 320210348314,
 320210463004,
 320210315549,
 320210372893,
 320210323754,
 320210520364,
 320210495795,
 320210463030,
 320210479414,
 320210397498,
 320210422075,
 320210446652,
 320210291007,
 320210504001,
 320210504002,
 320210274627,
 320210479428,
 320210291016,
 320210315598,
 320210422097,
 320210274642,
 320210495828,
 320210528596,
 320210266457,
 320210291039,
 320210282853,
 320210299239,
 320210291053,
 320210291055,
 320210413935,
 320210454895,
 320210291060,
 320210291063,
 320210323831,
 320210430329,
 320210487673,
 320210323835,
 320210463099,
 320210372989,
 320210381182,
 320210299263,
 320210340225,
 320210504066,
 320210266506,
 320210520461,
 320210332048,
 320210373008,
 320210397586,
 320210332051,
 320210364824,
 320210520473,
 320210438560,
 320210413987,
 320210348451,
 320210463145,
 320210332079,
 320210463152,
 320210422195,
 320210446771,
 320210487733,
 320210504117,
 320210520504,
 320210274748,
 320210364861,
 320210528701,
 320210389439,
 320210520514,
 320210373060,
 320210315719,
 320210266569,
 320210422218,
 320210487755,
 320210291149,
 320210504141,
 320210282959,
 320210266576,
 320210463185,
 320210282970,
 320210348508,
 320210364894,
 320210520544,
 320210356708,
 320210373093,
 320210463212,
 320210414078,
 320210405895,
 320210430476,
 320210283025,
 320210274834,
 320210340371,
 320210323986,
 320210528789,
 320210520597,
 320210307614,
 320210487842,
 320210324013,
 320210356790,
 320210479671,
 320210324025,
 320210446906,
 320210422333,
 320210356798,
 320210340417,
 320210455105,
 320210283075,
 320210266692,
 320210389578,
 320210430545,
 320210324050,
 320210430549,
 320210397783,
 320210455130,
 320210283100,
 320210438754,
 320210307691,
 320210348655,
 320210455151,
 320210406003,
 320210479732,
 320210414197,
 320210479734,
 320210504310,
 320210406011,
 320210455167,
 320210266761,
 320210324105,
 320210528906,
 320210381453,
 320210438797,
 320210496144,
 320210414225,
 320210340502,
 320210504343,
 320210504345,
 320210438813,
 320210381472,
 320210504364,
 320210365101,
 320210430640,
 320210381493,
 320210430647,
 320210438839,
 320210348738,
 320210275011,
 320210447044,
 320210356934,
 320210356943,
 320210488017,
 320210315989,
 320210381530,
 320210291425,
 320210275042,
 320210291427,
 320210520806,
 320210438888,
 320210397933,
 320210291440,
 320210512625,
 320210340594,
 320210520819,
 320210512628,
 320210291445,
 320210365179,
 320210504444,
 320210332414,
 320210283271,
 320210529033,
 320210324237,
 320210332432,
 320210479889,
 320210512658,
 320210512660,
 320210307862,
 320210471703,
 320210266904,
 320210406168,
 320210348837,
 320210389797,
 320210397998,
 320210447151,
 320210529070,
 320210463546,
 320210414400,
 320210291523,
 320210381642,
 320210357076,
 320210496340,
 320210529109,
 320210439006,
 320210520928,
 320210406242,
 320210357092,
 320210283364,
 320210348907,
 320210439019,
 320210520942,
 320210316151,
 320210414463,
 320210324352,
 320210373508,
 320210307974,
 320210291592,
 320210299788,
 320210480014,
 320210439063,
 320210471837,
 320210488222,
 320210275231,
 320210291616,
 320210480033,
 320210299807,
 320210471846,
 320210267048,
 320210471849,
 320210488236,
 320210529202,
 320210430908,
 320210299839,
 320210291652,
 320210529226,
 320210357200,
 320210414544,
 320210455516,
 320210422749,
 320210365405,
 320210521055,
 320210291687,
 320210381801,
 320210381803,
 320210512876,
 320210308075,
 320210471918,
 320210349038,
 320210316272,
 320210299889,
 320210316282,
 320210324475,
 320210291714,
 320210488323,
 320210398215,
 320210324488,
 320210455561,
 320210512909,
 320210496539,
 320210414620,
 320210275363,
 320210521127,
 320210316328,
 320210299945,
 320210431018,
 320210299947,
 320210422829,
 320210357293,
 320210390067,
 320210398259,
 320210332724,
 320210267190,
 320210299959,
 320210414648,
 320210463801,
 320210340915,
 320210365495,
 320210267197,
 320210365503,
 320210357312,
 320210373701,
 320210512969,
 320210488395,
 320210472011,
 320210406495,
 320210414687,
 320210340961,
 320210504801,
 320210349159,
 320210349162,
 320210275437,
 320210398318,
 320210513009,
 320210398326,
 320210488438,
 320210406521,
 320210357375,
 320210300031,
 320210300034,
 320210373765,
 320210267273,
 320210275465,
 320210488464,
 320210349201,
 320210332818,
 320210357398,
 320210316441,
 320210349213,
 320210275491,
 320210316455,
 320210513070,
 320210521265,
 320210447541,
 ...}

In [544]:
col1 = ['증권번호','모집년월','기준년월','경과월수','보험료유지회차', '모집계약건수','보유계약건수','최종납입횟수',
        '보험기간시작일자','최종납입년월','계약상태명','계약상태세부명','계약상태세부일자','배당상품여부',
        '모집계약환산보험료', '보유계약환산보험료', '납입계약환산보험료']

samp1 = df[df['증권번호']==320210313295].sort_values(by='기준년월')[col1]
samp1

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,계약상태명,계약상태세부명,계약상태세부일자,배당상품여부,모집계약환산보험료,보유계약환산보험료,납입계약환산보험료
125374,320210313295,202102,202102,1,1,1,1,1,20210204,202102,정상,정상,20210204,0,255000,255000,255000
120581,320210313295,202102,202103,2,2,1,1,2,20210204,202103,정상,정상,20210204,0,255000,255000,255000
113973,320210313295,202102,202104,3,3,1,1,3,20210204,202104,정상,정상,20210204,0,255000,255000,255000
108982,320210313295,202102,202105,4,4,1,1,4,20210204,202105,정상,정상,20210204,0,255000,255000,255000
104003,320210313295,202102,202106,5,5,1,1,5,20210204,202106,정상,정상,20210204,0,255000,255000,255000
96196,320210313295,202102,202107,6,6,1,1,6,20210204,202107,정상,정상,20210204,0,255000,255000,255000
93897,320210313295,202102,202108,7,7,1,1,7,20210204,202108,정상,정상,20210204,0,255000,255000,255000
86035,320210313295,202102,202109,8,8,1,1,8,20210204,202109,정상,정상,20210204,0,255000,255000,255000
81091,320210313295,202102,202110,9,9,1,1,9,20210204,202110,정상,정상,20210204,0,255000,255000,255000
80301,320210313295,202102,202111,10,10,1,1,10,20210204,202111,정상,정상,20210204,0,255000,255000,255000
72105,320210313295,202102,202112,11,11,1,1,11,20210204,202112,정상,정상,20210204,0,255000,255000,255000
67103,320210313295,202102,202201,12,12,1,1,12,20210204,202201,정상,정상,20210204,0,255000,255000,255000
65134,320210313295,202102,202202,13,13,1,1,13,20210204,202202,정상,정상,20210204,0,255000,255000,255000
58805,320210313295,202102,202203,14,14,1,1,14,20210204,202203,정상,정상,20210204,0,255000,255000,255000
53861,320210313295,202102,202204,15,15,1,1,15,20210204,202204,정상,정상,20210204,0,255000,255000,255000
48708,320210313295,202102,202205,16,16,1,1,16,20210204,202205,정상,정상,20210204,0,255000,255000,255000
44870,320210313295,202102,202206,17,17,1,1,17,20210204,202206,정상,정상,20210204,0,255000,255000,255000
38948,320210313295,202102,202207,18,18,1,1,18,20210204,202207,정상,정상,20210204,0,255000,255000,255000
31629,320210313295,202102,202208,19,19,1,0,18,20210204,202207,정상,정상,20220901,0,255000,0,0
29043,320210313295,202102,202209,20,20,1,1,20,20210204,202209,정상,정상,20220916,0,255000,255000,255000
20715,320210313295,202102,202210,21,21,1,0,20,20210204,202209,정상,정상,20221101,0,255000,0,0
19112,320210313295,202102,202211,22,22,1,0,21,20210204,202210,정상,연체,20221101,0,255000,0,0
10892,320210313295,202102,202212,23,23,1,0,21,20210204,202210,정상,연체,20230101,0,255000,0,0
9522,320210313295,202102,202301,24,24,1,0,22,20210204,202211,정상,연체,20230201,0,255000,0,0
1160,320210313295,202102,202302,25,25,1,0,22,20210204,202211,실효,실효유예,20230201,0,255000,0,0

In [518]:
samp1

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,계약상태세부명,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
125374,320210313295,202102,202102,1,1,1,1,1,20210204,202102,정상,255000,255000,255000,255000
120581,320210313295,202102,202103,2,2,1,1,2,20210204,202103,정상,255000,255000,255000,255000
113973,320210313295,202102,202104,3,3,1,1,3,20210204,202104,정상,255000,255000,255000,255000
108982,320210313295,202102,202105,4,4,1,1,4,20210204,202105,정상,255000,255000,255000,255000
104003,320210313295,202102,202106,5,5,1,1,5,20210204,202106,정상,255000,255000,255000,255000
96196,320210313295,202102,202107,6,6,1,1,6,20210204,202107,정상,255000,255000,255000,255000
93897,320210313295,202102,202108,7,7,1,1,7,20210204,202108,정상,255000,255000,255000,255000
86035,320210313295,202102,202109,8,8,1,1,8,20210204,202109,정상,255000,255000,255000,255000
81091,320210313295,202102,202110,9,9,1,1,9,20210204,202110,정상,255000,255000,255000,255000
80301,320210313295,202102,202111,10,10,1,1,10,20210204,202111,정상,255000,255000,255000,255000
72105,320210313295,202102,202112,11,11,1,1,11,20210204,202112,정상,255000,255000,255000,255000
67103,320210313295,202102,202201,12,12,1,1,12,20210204,202201,정상,255000,255000,255000,255000
65134,320210313295,202102,202202,13,13,1,1,13,20210204,202202,정상,255000,255000,255000,255000
58805,320210313295,202102,202203,14,14,1,1,14,20210204,202203,정상,255000,255000,255000,255000
53861,320210313295,202102,202204,15,15,1,1,15,20210204,202204,정상,255000,255000,255000,255000
48708,320210313295,202102,202205,16,16,1,1,16,20210204,202205,정상,255000,255000,255000,255000
44870,320210313295,202102,202206,17,17,1,1,17,20210204,202206,정상,255000,255000,255000,255000
38948,320210313295,202102,202207,18,18,1,1,18,20210204,202207,정상,255000,255000,255000,255000
31629,320210313295,202102,202208,19,19,1,0,18,20210204,202207,정상,255000,0,255000,0
29043,320210313295,202102,202209,20,20,1,1,20,20210204,202209,정상,255000,255000,255000,255000
20715,320210313295,202102,202210,21,21,1,0,20,20210204,202209,정상,255000,0,255000,0
19112,320210313295,202102,202211,22,22,1,0,21,20210204,202210,연체,255000,0,255000,0
10892,320210313295,202102,202212,23,23,1,0,21,20210204,202210,연체,255000,0,255000,0
9522,320210313295,202102,202301,24,24,1,0,22,20210204,202211,연체,255000,0,255000,0
1160,320210313295,202102,202302,25,25,1,0,22,20210204,202211,실효유예,255000,0,255000,0

In [169]:
df_14 = df[df['보험료유지회차'] == 14]
df_14[col1].groupby('보유계약건수').size()

보유계약건수
0     379
1    2104
dtype: int64

In [472]:
df_15 = df[df['보험료유지회차'] == 15]
df_15[col1].groupby('보유계약건수').size() #15회차 이전 미유지 건 포함

보유계약건수
0     412
1    2071
dtype: int64

In [474]:
df[df['증권번호']==320210265286][col1].sort_values(by='기준년월') #2차년도 15회차시 미유지이나 추후 다시 유지계약으로 변환

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
121353,320210265286,202102,202102,1,1,1,1,1,20210201,202102,43,130000,130000,130000,130000
116254,320210265286,202102,202103,2,2,1,1,2,20210201,202103,43,130000,130000,130000,130000
110946,320210265286,202102,202104,3,3,1,1,3,20210201,202104,43,130000,130000,130000,130000
107079,320210265286,202102,202105,4,4,1,1,4,20210201,202105,43,130000,130000,130000,130000
101961,320210265286,202102,202106,5,5,1,1,5,20210201,202106,43,130000,130000,130000,130000
99770,320210265286,202102,202107,6,6,1,1,6,20210201,202107,43,130000,130000,130000,130000
90776,320210265286,202102,202108,7,7,1,1,7,20210201,202108,43,130000,130000,130000,130000
90631,320210265286,202102,202109,8,8,1,1,8,20210201,202109,43,130000,130000,130000,130000
85703,320210265286,202102,202110,9,9,1,1,9,20210201,202110,43,130000,130000,130000,130000
75703,320210265286,202102,202111,10,10,1,1,10,20210201,202111,43,130000,130000,130000,130000
74960,320210265286,202102,202112,11,11,1,1,11,20210201,202112,43,130000,130000,130000,130000
70568,320210265286,202102,202201,12,12,1,1,12,20210201,202201,43,130000,130000,130000,130000
61327,320210265286,202102,202202,13,13,1,1,13,20210201,202202,43,130000,130000,130000,130000
55498,320210265286,202102,202203,14,14,1,1,14,20210201,202203,43,130000,130000,130000,130000
50432,320210265286,202102,202204,15,15,1,0,14,20210201,202203,43,130000,0,130000,0
45385,320210265286,202102,202205,16,16,1,0,15,20210201,202204,43,130000,0,130000,0
40966,320210265286,202102,202206,17,17,1,0,16,20210201,202205,43,130000,0,130000,0
35305,320210265286,202102,202207,18,18,1,0,16,20210201,202205,43,130000,0,130000,0
35270,320210265286,202102,202208,19,19,1,1,19,20210201,202208,43,130000,130000,130000,130000
25319,320210265286,202102,202209,20,20,1,0,19,20210201,202208,43,130000,0,130000,0
24707,320210265286,202102,202210,21,21,1,1,21,20210201,202210,43,130000,130000,130000,130000
15530,320210265286,202102,202211,22,22,1,1,22,20210201,202211,43,130000,130000,130000,130000
15031,320210265286,202102,202212,23,23,1,1,23,20210201,202212,43,130000,130000,130000,130000
5192,320210265286,202102,202301,24,24,1,1,24,20210201,202301,43,130000,130000,130000,130000
4656,320210265286,202102,202302,25,25,1,1,25,20210201,202302,43,130000,130000,130000,130000

In [476]:
df[df['증권번호']==320210443746][col1].sort_values(by='기준년월') #뭔지 잘 모르겠는 계약

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
122361,320210443746,202102,202102,1,1,1,1,1,20210218,202102,57,121000,121000,121000,121000
117002,320210443746,202102,202103,2,2,1,1,2,20210218,202103,57,121000,121000,121000,121000
111515,320210443746,202102,202104,3,3,1,1,3,20210218,202104,57,121000,121000,121000,121000
106491,320210443746,202102,202105,4,4,1,1,4,20210218,202105,57,121000,121000,121000,121000
102850,320210443746,202102,202106,5,5,1,1,5,20210218,202106,57,121000,121000,121000,121000
100263,320210443746,202102,202107,6,6,1,1,6,20210218,202107,57,121000,121000,121000,121000
91249,320210443746,202102,202108,7,7,1,1,7,20210218,202108,57,121000,121000,121000,121000
90137,320210443746,202102,202109,8,8,1,1,8,20210218,202109,57,121000,121000,121000,121000
83910,320210443746,202102,202110,9,9,1,1,9,20210218,202110,57,121000,121000,121000,121000
76227,320210443746,202102,202111,10,10,1,1,10,20210218,202111,57,121000,121000,121000,121000
73869,320210443746,202102,202112,11,11,1,1,11,20210218,202112,57,121000,121000,121000,121000
70064,320210443746,202102,202201,12,12,1,0,11,20210218,202112,57,121000,0,121000,0
62433,320210443746,202102,202202,13,13,1,1,13,20210218,202202,57,121000,121000,121000,121000
57405,320210443746,202102,202203,14,14,1,1,14,20210218,202203,57,121000,121000,121000,121000
51006,320210443746,202102,202204,15,15,1,0,14,20210218,202203,57,121000,0,121000,0
47393,320210443746,202102,202205,16,16,1,1,16,20210218,202205,57,121000,101800,121000,101800
42138,320210443746,202102,202206,17,17,1,1,17,20210218,202206,57,121000,101800,121000,101800
37112,320210443746,202102,202207,18,18,1,1,18,20210218,202207,57,121000,101800,121000,101800
33621,320210443746,202102,202208,19,19,1,1,19,20210218,202208,57,121000,101800,121000,101800
26610,320210443746,202102,202209,20,20,1,1,20,20210218,202209,57,121000,101800,121000,101800
23708,320210443746,202102,202210,21,21,1,1,21,20210218,202210,57,121000,101800,121000,101800
16580,320210443746,202102,202211,22,22,1,1,22,20210218,202211,57,121000,101800,121000,101800
13896,320210443746,202102,202212,23,23,1,1,23,20210218,202212,57,121000,101800,121000,101800
6248,320210443746,202102,202301,24,24,1,0,23,20210218,202212,57,121000,0,121000,0
3565,320210443746,202102,202302,25,25,1,0,23,20210218,202212,57,121000,0,121000,0

In [271]:
df_15[(df_15['보유계약건수']==0)&(df_15['모집계약환산보험료']<=0)][col1]
# df[df['증권번호']==320210507443][col1].sort_values(by='기준년월') #특정 증번에 대한 상세내역

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
50901,320210520928,202102,202204,15,15,0,0,9,20210226,202110,60,0,0,40840,0
51735,320210468256,202102,202204,15,15,0,0,6,20210222,202107,48,0,0,142300,0
53938,320210467572,202102,202204,15,15,0,0,1,20210222,202102,58,0,0,182000,0
54697,320210507443,202102,202204,15,15,0,0,1,20210225,202102,52,0,0,200000,0

In [269]:
df[df['증권번호']==320210507443][col1].sort_values(by='기준년월')

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
124740,320210507443,202102,202102,1,1,1,1,1,20210225,202102,52,200000,200000,200000,200000
119870,320210507443,202102,202103,2,2,1,0,1,20210225,202102,52,200000,0,200000,0
115236,320210507443,202102,202104,3,3,0,0,1,20210225,202102,52,0,0,200000,0
110219,320210507443,202102,202105,4,4,0,0,1,20210225,202102,52,0,0,200000,0
103570,320210507443,202102,202106,5,5,0,0,1,20210225,202102,52,0,0,200000,0
98216,320210507443,202102,202107,6,6,0,0,1,20210225,202102,52,0,0,200000,0
95056,320210507443,202102,202108,7,7,0,0,1,20210225,202102,52,0,0,200000,0
88305,320210507443,202102,202109,8,8,0,0,1,20210225,202102,52,0,0,200000,0
81488,320210507443,202102,202110,9,9,0,0,1,20210225,202102,52,0,0,200000,0
78554,320210507443,202102,202111,10,10,0,0,1,20210225,202102,52,0,0,200000,0
72809,320210507443,202102,202112,11,11,0,0,1,20210225,202102,52,0,0,200000,0
67708,320210507443,202102,202201,12,12,0,0,1,20210225,202102,52,0,0,200000,0
64809,320210507443,202102,202202,13,13,0,0,1,20210225,202102,52,0,0,200000,0
58136,320210507443,202102,202203,14,14,0,0,1,20210225,202102,52,0,0,200000,0
54697,320210507443,202102,202204,15,15,0,0,1,20210225,202102,52,0,0,200000,0
49478,320210507443,202102,202205,16,16,0,0,1,20210225,202102,52,0,0,200000,0
43261,320210507443,202102,202206,17,17,0,0,1,20210225,202102,52,0,0,200000,0
39412,320210507443,202102,202207,18,18,0,0,1,20210225,202102,52,0,0,200000,0
32330,320210507443,202102,202208,19,19,0,0,1,20210225,202102,52,0,0,200000,0
29153,320210507443,202102,202209,20,20,0,0,1,20210225,202102,52,0,0,200000,0
21398,320210507443,202102,202210,21,21,0,0,1,20210225,202102,52,0,0,200000,0
18413,320210507443,202102,202211,22,22,0,0,1,20210225,202102,52,0,0,200000,0
11622,320210507443,202102,202212,23,23,0,0,1,20210225,202102,52,0,0,200000,0
8814,320210507443,202102,202301,24,24,0,0,1,20210225,202102,52,0,0,200000,0
1173,320210507443,202102,202302,25,25,0,0,1,20210225,202102,52,0,0,200000,0

In [345]:
# 증권번호로 그룹화, 기준년월 기준으로 정렬
df_1 = df.sort_values(by=["증권번호","기준년월"])[col1]

# 직전 보유계약건수 값을 확인하기 위해 shift() 함수 사용
df_1["previous_s"] = df_1.groupby("증권번호")['보유계약건수'].shift(1)

# 보유계약건수가 1에서 0으로 바뀌는 패턴 찾기
df_2 = df_1[(df_1['보유계약건수']==0) & (df_1['previous_s']==1)]

print(len(set(df_2['증권번호'])))
print(len(df_2))

900
1412

In [347]:
df_2[df_2['증권번호']==320210530368]

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료,previous_s
92253,320210530368,202102,202108,7,7,1,0,6,20210228,202107,64,65400,0,65400,0,1.0
57146,320210530368,202102,202203,14,14,1,0,13,20210228,202202,64,65400,0,65400,0,1.0
22451,320210530368,202102,202210,21,21,1,0,20,20210228,202209,64,65400,0,65400,0,1.0
12519,320210530368,202102,202212,23,23,1,0,22,20210228,202211,64,65400,0,65400,0,1.0

In [426]:
df_2[df_2['증권번호']==320210530368].sort_values(["증권번호",'보험료유지회차']).groupby('증권번호').first()

,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료,previous_s
증권번호,,,,,,,,,,,,,,,
320210530368,202102,202108,7,7,1,0,6,20210228,202107,64,65400,0,65400,0,1.0

In [448]:
df_3 = df_2.sort_values(by=['증권번호','기준년월']).groupby('증권번호').first().reset_index()
df_3[df_3['보험료유지회차']==15]

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,만기년수,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료,previous_s
0,320210260486,202102,202204,15,15,1,0,14,20210201,202203,62,71100,0,71100,0,1.0
1,320210260794,202102,202204,15,15,1,0,14,20210201,202203,28,120000,0,120000,0,1.0
7,320210262280,202102,202204,15,15,1,0,14,20210201,202203,47,120000,0,120000,0,1.0
16,320210265286,202102,202204,15,15,1,0,14,20210201,202203,43,130000,0,130000,0,1.0
38,320210269685,202102,202204,15,15,1,0,14,20210201,202203,48,370000,0,370000,0,1.0
97,320210284398,202102,202204,15,15,1,0,14,20210202,202203,57,206200,0,206200,0,1.0
113,320210288090,202102,202204,15,15,1,0,14,20210202,202203,49,101000,0,101000,0,1.0
119,320210289422,202102,202204,15,15,1,0,14,20210202,202203,73,100000,0,100000,0,1.0
126,320210291055,202102,202204,15,15,1,0,14,20210202,202203,63,36700,0,36700,0,1.0
127,320210291060,202102,202204,15,15,1,0,14,20210202,202203,64,37800,0,37800,0,1.0
169,320210304211,202102,202204,15,15,1,0,14,20210203,202203,51,100300,0,100300,0,1.0
180,320210307296,202102,202204,15,15,1,0,14,20210203,202203,54,63000,0,63000,0,1.0
207,320210314492,202102,202204,15,15,1,0,14,20210204,202203,67,151500,0,151500,0,1.0
212,320210316282,202102,202204,15,15,1,0,14,20210204,202203,84,55000,0,55000,0,1.0
230,320210322614,202102,202204,15,15,1,0,14,20210204,202203,54,260000,0,260000,0,1.0
280,320210345884,202102,202204,15,15,1,0,14,20210205,202203,66,20000,0,20000,0,1.0
289,320210349213,202102,202204,15,15,1,0,14,20210205,202203,50,289000,0,289000,0,1.0
295,320210351520,202102,202204,15,15,1,0,14,20210205,202203,54,220000,0,220000,0,1.0
340,320210366222,202102,202204,15,15,1,0,14,20210208,202203,59,70500,0,70500,0,1.0
358,320210374813,202102,202204,15,15,1,0,15,20210209,202204,46,98629,0,98629,0,1.0
379,320210383341,202102,202204,15,15,1,0,14,20210209,202203,44,87160,0,87160,0,1.0
416,320210402718,202102,202204,15,15,1,0,14,20210215,202203,61,128100,0,128100,0,1.0
427,320210406741,202102,202204,15,15,1,0,14,20210215,202203,32,133000,0,133000,0,1.0
435,320210409233,202102,202204,15,15,1,0,14,20210215,202203,75,94000,0,94000,0,1.0
452,320210414197,202102,202204,15,15,1,0,14,20210216,202203,64,126500,0,126500,0,1.0
568,320210452597,202102,202204,15,15,1,0,14,20210219,202203,48,100000,0,100000,0,1.0
574,320210453548,202102,202204,15,15,1,0,14,20210219,202203,69,100000,0,100000,0,1.0
629,320210467592,202102,202204,15,15,1,0,14,20210222,202203,74,250000,0,250000,0,1.0
634,320210470133,202102,202204,15,15,1,0,14,20210222,202203,32,138300,0,138300,0,1.0
646,320210474919,202102,202204,15,15,1,0,14,20210223,202203,70,190000,0,190000,0,1.0
668,320210481402,202102,202204,15,15,1,0,14,20210223,202203,49,151000,0,151000,0,1.0
707,320210491167,202102,202204,15,15,1,0,14,20210224,202203,48,155000,0,155000,0,1.0
720,320210493410,202102,202204,15,15,1,0,14,20210224,202203,59,83000,0,83000,0,1.0
743,320210500122,202102,202204,15,15,1,0,14,20210225,202203,65,59800,0,59800,0,1.0
769,320210506204,202102,202204,15,15,1,0,14,20210225,202203,58,52200,0,52200,0,1.0
779,320210507898,202102,202204,15,15,1,0,15,20210225,202204,51,19731,0,19731,0,1.0
785,320210508748,202102,202204,15,15,1,0,15,20210225,202204,68,20000,0,20000,0,1.0
797,320210511809,202102,202204,15,15,1,0,14,20210225,202203,75,200000,0,200000,0,1.0
808,320210515701,202102,202204,15,15,1,0,14,20210226,202203,50,140100,0,140100,0,1.0

In [ ]:
320210470133
320210515701
320210443746
320210265286
320210530368

In [516]:
df[df['증권번호']==320210530368][col1].sort_values(by='기준년월')

,증권번호,모집년월,기준년월,경과월수,보험료유지회차,모집계약건수,보유계약건수,최종납입횟수,보험기간시작일자,최종납입년월,계약상태세부명,모집계약환산보험료,보유계약환산보험료,잔존계약환산보험료,납입계약환산보험료
123347,320210530368,202102,202102,1,1,1,1,1,20210228,202102,정상,65400,65400,65400,65400
118686,320210530368,202102,202103,2,2,1,1,2,20210228,202103,정상,65400,65400,65400,65400
112223,320210530368,202102,202104,3,3,1,1,3,20210228,202104,정상,65400,65400,65400,65400
109413,320210530368,202102,202105,4,4,1,1,4,20210228,202105,정상,65400,65400,65400,65400
102347,320210530368,202102,202106,5,5,1,1,5,20210228,202106,정상,65400,65400,65400,65400
97185,320210530368,202102,202107,6,6,1,1,6,20210228,202107,정상,65400,65400,65400,65400
92253,320210530368,202102,202108,7,7,1,0,6,20210228,202107,정상,65400,0,65400,0
89326,320210530368,202102,202109,8,8,1,1,8,20210228,202109,정상,65400,65400,65400,65400
82553,320210530368,202102,202110,9,9,1,1,9,20210228,202110,정상,65400,65400,65400,65400
78742,320210530368,202102,202111,10,10,1,1,10,20210228,202111,정상,65400,65400,65400,65400
72478,320210530368,202102,202112,11,11,1,1,11,20210228,202112,정상,65400,65400,65400,65400
67359,320210530368,202102,202201,12,12,1,1,12,20210228,202201,정상,65400,65400,65400,65400
62230,320210530368,202102,202202,13,13,1,1,13,20210228,202202,정상,65400,65400,65400,65400
57146,320210530368,202102,202203,14,14,1,0,13,20210228,202202,정상,65400,0,65400,0
52030,320210530368,202102,202204,15,15,1,1,15,20210228,202204,정상,65400,65400,65400,65400
48747,320210530368,202102,202205,16,16,1,1,16,20210228,202205,정상,65400,65400,65400,65400
43488,320210530368,202102,202206,17,17,1,1,17,20210228,202206,정상,65400,65400,65400,65400
37151,320210530368,202102,202207,18,18,1,1,18,20210228,202207,정상,65400,65400,65400,65400
33349,320210530368,202102,202208,19,19,1,1,19,20210228,202208,정상,65400,65400,65400,65400
27478,320210530368,202102,202209,20,20,1,1,20,20210228,202209,정상,65400,65400,65400,65400
22451,320210530368,202102,202210,21,21,1,0,20,20210228,202209,정상,65400,0,65400,0
17361,320210530368,202102,202211,22,22,1,1,22,20210228,202211,연체,65400,65400,65400,65400
12519,320210530368,202102,202212,23,23,1,0,22,20210228,202211,정상,65400,0,65400,0
7817,320210530368,202102,202301,24,24,1,0,23,20210228,202212,정상,65400,0,65400,0
2266,320210530368,202102,202302,25,25,1,0,23,20210228,202212,연체,65400,0,65400,0